### ISSUE TITLE
AnnotationProxy throws an exception when copying enums or classes

### ISSUE THREAD

**Issue by lhkbob** [grouplens/grapht#106]
Under the hood, AnnotationProxy's copyAnnotationValue() checks if something is an array for a shallow copy, or it returns it as is if it's a primitive, primitive wrapper, String, or annotation.  However, if it's not one of those types it throws an exception. Annotations can reference classes and enums and those should not fail.

If I remember correctly, the exception is important for catching invalid configuration before the proxy is built, so we can't just assume anything other than an array is immutable.

**Comment by elehack** [comment]
I believe this is fixed by #116.
