### ISSUE TITLE
Use MDC to log classes being instantiated

### ISSUE THREAD

**Issue by ghost** [grouplens/grapht#52]
It seems useful to log instantiation attempts in the SLF4J [MDC](http://www.slf4j.org/api/org/slf4j/MDC.html) (more docs over [here at Logback](http://logback.qos.ch/manual/mdc.html).  That way log messages that happen during component instantiation are tagged with the component being instantiated.

What we need to do in order to do this is to modify the instantiation logic in a few places:

- [ ] Create support code to 'push' and 'pop' MDC values, since our code is recursive. The [MDC API](http://www.slf4j.org/api/org/slf4j/MDC.html) is implemented in terms of setting and removing; however, when we set the value for for our key, there may be a different value already in place because we are being called to satisfy some dependency. So we need to be able to save the old value, and restore it when a context is done. `MDCCloseable` may already do that, or it may delete the key; we should check. We already have this code in LensKit; we can copy it from there if needed.
- [ ] Add support to `ClassInstantiator` to record the class being instantiated in the MDC, under `org.grouplens.grapht.class`. We may also want to record the injection point as a `org.grouplens.grapht.injectionPoint` for each injection point that is being satisfied.
- [ ] Add support to `Instantiators.ProviderInstantiator` to record the provider being invoked when invoking a provider.
- [ ] Improve logging as appropriate (for example, `ProviderInstantiator` doesn't emit a log message before it runs the provider; it should emit a `trace`-level message that it is starting the provider, with the provider's `toString`).

**Comment by elehack** [comment]
Done in #109.
