### ISSUE TITLE
Support container lifecycles and Java PostConstruct/PreDestroy annotations

### ISSUE THREAD

**Issue by ghost** [grouplens/grapht#67]
We want to be able to have a lifecycle scope that gets associated with graph construction operations. There are a couple of implications of this scope:

- Instantiator memoization or caching should be per-scope, rather than global. This may allow us to simplify the design for caching.
- Closing a scope tears down its objects (closing `Closeable` objects, calling `PreDestroy` methods). Objects need to be torn down in *reverse* order, so the most recently-created object is destroyed first. We also need to manage exceptions, so that we tear down all objects even if an early one fails, and then throw an appropriate exception at the end of the teardown process.

There are several pieces to this:

- [ ] Create the lifecycle manager / object scope class. We could call this `ComponentLifecycleScope`?
- [ ] Connect the lifecycle manager class to the instantiators.
    - [ ] Class instantiator needs to register the instance it creates with the lifecycle manager for shutdown, as well as call the `PostConstruct` methods. We can handle `PostConstruct` methods as no-arg injection points; we should probably sort the injection points so that the no-arg ones are handled last, and `PostConstruct` ones come after `Inject` ones.
    - [ ] Provider instantiator: it should be configurable whether the provided object is registered with the lifecycle. I am inclined to say that it should be registered by default. I think it is safe to assume that the provider will call any `PostConstruct` methods, but we should review the relevant standards.
    - [ ] Instance instantiator: the object should not be registered with the lifecycle. We might want to make it configurable that the object can be registered with the lifecycle, and default to not registering it, but I don't think we need to register them with the lifecycle in any reasonable case. However, it may be worth reviewing the relevant JSR to see if there are any specific requirements on this matter.
- [ ] Modify the `Injector` interface to have a `close` method (extending `AutoCloseable` if we decide to drop Java 6 compatibility).
- [ ] Modify the `DefaultInjector` to create a lifecycle manager and use it to manage lifecycles for the objects it creates, closing the lifecycle manager in its `close()` method.

Once all this is done, then we can hook it up to LensKit. This should all be in a new feature branch, to be merged sometime after we release Grapht 0.10.

**Comment by elehack** [comment]
We're going to need this for LensKit 3.0.

**Comment by elehack** [comment]
There are a few design decisions we're going to have to make here. Does @lhkbob have any input?

**Comment by mdekstrand** [comment]
Done and merged.
